#!/bin/bash

# Clean up old diffs
{
    ls -1 *.diff | xargs rm 
} &> /dev/null

printf "%s\n\n" "Running all tests"

GREEN="\e[0;32m"
RED="\e[0;31m"
END="\e[0m"

BASE=$(pwd)
TESTS=$(ls -d */)
PASSED=0
FAILED=0
cd ..

for TEST in $TESTS; do
    printf "  * running test ${TEST%/}: "
    DIR=$BASE/$TEST
    SETUP=$(cat $DIR/setup)
    ./bash-reduce $SETUP $DIR/input > $DIR/result
    diff $DIR/result $DIR/expected > /dev/null
    if [[ $? -eq 0 ]]; then
        printf "${GREEN}passed${END}!\n"
        PASSED=$((PASSED+1))
    else
        diff $DIR/result $DIR/expected > "$BASE/${TEST%/}.diff"
        printf "${RED}failed${END}\n"
        FAILED=$((FAILED+1))
    fi
    rm $DIR/result
done

if [[ $FAILED -eq 0 ]]; then
    printf "\nAll tests ${GREEN}PASSED${END}!\n"
else
    printf "\n$FAILED test(s) ${RED}FAILED${END}! read diff file for more info.\n"
fi
